# If you have any questions, you can contact me at:
- marco.feder@sissa.it 

Office: A-731 (7-th floor, SISSA)

At the end of this notebook there are some exercises aimed to absolute Python beginners.

### Comments
A comment in Python starts with `#` and extends to the end of the physical line.

### Arithmetic operations

Python notebooks are interactive. You can use cells as calculators. Operations work as one would expect:

In [ ]:
print(2*22) #multiplication 
print(20+2) #addition 
print(20/2) #floating point division 

#Power operator
print(5**2) #and not 5^2

#Reminder of division
print(20%2)

### Assignment
In Python, you can assign a value to a variable using the *assignment* operator `=`

In [ ]:
a = 2 
print("a = ", a)
a = a + 2 #This is not an equation! The value of a is incremented 
print("a after incrementing = ", a)

Python comes with many types. (You can think of a type as a particular implementation of a concept). Let's see some of them.

In [ ]:
#You can query the type of a variable
print(type(a)) #integer
print(type(2.5)) #float


print(type(True))
print(type(False))

**Strings**

A string is a sequence of characters.

In [ ]:
s = "this is a string"
print(s)
s2 = 'this is another string' 
print(s)

#You can do operations supported by objects of type string. For instance, you can concatenate two strings using the + operator
print(s + " and " +s2)

You can access an element of the strings above by using the `[]` operator.

**Note:** Python uses zero-based indexing. Therefore, first element has index 0, the second has index 1, and so on.
The last element can be accessed with the index -1

In [ ]:
print("s[2] = ",s[2])

In [ ]:
#Let's access some other elements of the string
print("s[0] = ",s[0])
print("s[3] = ",s[3])
print("s[5] = ",s[5])

print("s[-1] = ", s[-1]) 

#What happens if you try to access element with index 20
# s[20] --> string index out of range

### Keywords
- Python keywords cannot be used as variable names.

In [ ]:

if = 2 
#The same holds for all the other keywords

### Control flow
- `if`, `elif`, `else` 

``` python
if <condition1>:
    <body>
elif <condition2>:
    <body>
else:
    <body>
```

These are valid *Boolean expressions* that you can use
- `==`
- `!=`
- `<=`
- `>=`
- `and`
- `not`
- `or`

In [ ]:
d = 20
if (d>20):
  print("Greater than 20!")
else:
  print("Less or equal than 20!")

is_d_equal_to_20 = d==20 #this is valid! On the right, we get a boolean variable
print("is_d_equal_to_20 = ",is_d_equal_to_20)

b = True #Capital T (in C/C++ it's true)
if(b):
  print("b is true")


### Loops

* `for`
* `range([start,]stop[,step])` 

``` python
for <var> in <set_of_values>: 
    <body>
```

***Note:*** Ranges are closed on the left, and open on the right. (If you are curious: https://www.cs.utexas.edu/users/EWD/ewd08xx/EWD831.PDF)

In [ ]:
#Loop over the first ten integer numbers.
for i in range(11):
  print("i = ",i + 1)


start = 0
stop = 20
step = 2
for elem in range(start,stop,step):
  print("elem = ", elem)


``` python    
while <true_condition>:
    <body> 
```

In [ ]:
counter = 0
while(counter < 20):
  counter = counter +1
  print("counter = ", counter)

## Lists
 - mutable
 - resizable
 - heterogeneous container (you may have objects of different types)

 There are many ways to initialize a list:

In [ ]:
l = [] #this is an empty list
print(type(l)) 
ll = list() #this is another empty list
print("ll = ", ll)

In [ ]:
#You can initialize a list "manually"
lh = [1,2,5,6,7,4,2,3,5,7,8]
print("lh = ", lh)

In [ ]:
#You can initalize with a range:
lr = list(range(10)) #10 not included, as before
lr[3] = 20 #change element with index 3
print("lr = ", lr)

You can query the length (i.e. the number of elements) of a list with `len()`

In [ ]:
print("The length of lr is:", len(lr))

You can use the method `append()` to add an element at the end of the list. This is something that you may need whenever you have no a-priori knowledge of the length of your list.

In [ ]:
#append an element to empty list l
print("l = ", l)
l.append("this string")
print("l after first append(): ", l)
l.append("another string")
print("l after second append(): ", l)
print("l[-1]", l[-1]) #to get the last element.

There are many methods that you can play with. Have a look at the documentation of `list` and try to get familiar with it! https://docs.python.org/3/tutorial/datastructures.html

In [ ]:
#Other possible methods for a list:
l = [2,4,5,67,7,4]
print("The number 67 has index: ",l.index(67))
#You can clear a list:
l.clear()
print("l after clear(): ",l)

### Slicing
 - `list[start:stop:step]` note that `[start:stop)`
 - if omitted `start==0`
 - if `stop` is omitted means till last element **included**
 - if omitetted `step==1`

In [ ]:
l = [44,5,6,7,6,7,8,9,5,4,20]
print("Original list:", l)
start = 0
stop = 4
step = 1
print(l[start:stop])  # items start through stop-1
print(l[start:])  # items start through the rest of the list
print(l[:stop])  # items from the beginning through stop-1
print(l[:])  # a copy of the whole list
print(l[:-1])  # last element is *excluded*

### Sorting a list

You can sort a list `l` in two different ways:
- `l.sort()` sorts the list in place => original list is modified 
- `sorted(l)` returns a new list, and the original one is untouched

In [ ]:
l = [210,2,3,5,3,2,56,4,564,3]
print("l before sorting: ", l)
l.sort() #in-place sorting. The list l is modified
print("l after sorting: ", l)

In [ ]:
l = [210,2,3,5,3,2,56,4,564,3]
new_list = sorted(l) #returns a new list
print("original l: ", l)
print("new_list: ", new_list)

### Tuples
- immutable, cannot add or change objects after construction
- Can be created in different ways

In [ ]:
#Creation from an empty tuple
t = () #empty tuple

In [ ]:
#Create a tuple manually
th = (1,2,4,5,6,7,4,2, "a wild string")
print("t = ",t)

In [ ]:
#You can slice a tuple
tr = tuple(range(10))
print("tr = ", tr)
start = 0
stop = 4
step = 1
print(tr[start:stop])  # items start through stop-1
print(tr[start:])  # items start through the rest of the tuple
print(tr[:stop])  # items from the beginning through stop-1
print(tr[:])  # a copy of the tuple list
print(tr[:-1])  # last element is *excluded*

Unlike lists, tuples cannot be modified. You can see this from the error message given once the next cell is executed.

In [ ]:
t[2] = 4 #error 'tuple' object does not support item assignment

### Packing and unpacking tuples
- Can improve readability of your code

In [ ]:
#Tuple packing
first_elem = "Hi"
second_elem = "everybody"
packed_tuple = (a,b) #packing a and b into the tuple t
print("packed_tuple = ", packed_tuple)

In [ ]:
#Tuple unpacking
c, d = packed_tuple
print(c)
print(d)

When you unpack, you can ignore certain elements using `_`

In [ ]:
#Let's unpack **only** the "color" elements
tcolors = ("red", "blue","snake","yellow","dog")
r,b,_,y,_ = tcolors

What if your tuple is *really* long and you want just the first 4 elements?

In [ ]:
my_long_tuple = tuple(range(10000))
a,b,c,d, *rest = my_long_tuple
#if you want to ignore them, you can also do:
e,f,g,d, *_ = my_long_tuple

Creating a tuple is faster than creating a list.

In [ ]:
%timeit l = [1,2,3,5,6,4,5,4,5,4,6,6] #list
%timeit t = (1,2,3,5,6,4,5,4,5,4,6,6) #tuple

## Functions
```python
def function_name(arg1, arg2, arg3):
    '''Documentation'''
    body of the function
```
* `return` statement is optional

In [ ]:
def first_function(x):
  '''Our first function simply prints the given value.'''
  print("Your x = ", x)

first_function(20)

In [ ]:
help(first_function) #display the documentation of our function

In [ ]:
def my_string_function(s1,s2):
  return "Lab part for " + s1 + " and " + s2 + " students." #concatenation of strings

s1 = "DSSC"
s2 = "LM"
print(my_string_function(s1,s2))

In [ ]:
#Other simple examples
def func(x):
  x = x + 1 #increment x
  return x*x #take the square of the value just incremented


c = 20
print(func(c))

### Keyword and positional arguments
I can call the function `func` above in two ways:
- `func(20)` -> positional argument
- `func(x = 20)` -> keyword argument

*Positional argument* means that the argument must be provided in a correct position in a function call. 

Let's see an example:

In [ ]:
def info_about_you(name,language):
  print("Hi, I am "+ name + " and I speak " + language)

Here the order **matters**. Indeed, this makes sense:

In [ ]:
info_about_you("Pluto","german")

while this doesn't

In [ ]:
info_about_you("german","Pluto") #?!?!

- Keyword arguments are passed as a dictionary {key:value,...} (https://docs.python.org/3/tutorial/datastructures.html#dictionaries)
- With keyword arguments, the position doesn't matter:

In [ ]:
info_about_you(language="english",name="Winston")

We can pass any number of positional arguments using `*` when we define our function. The following function can take many names.

In [ ]:
def many_names(*names):
  for name in names:
    print("Hi " , name)

many_names("Luca", "Daniel", "Peter", "Martin")

In the same spirit, we can give any number of keyword arguments using `**`.

In [ ]:
def many_data(**names_and_ages):
  print(names_and_ages)

many_data(Mickey_Mouse = 20, Minnie = 18, Donald_Duck = 30)

In [ ]:
def foo(*my_positional_args,**my_keywords):
  print("my_positional_args",my_positional_args)
  print("my_keywords",my_keywords)

foo( 120,20,"Hello",my_key = "its value")

When you have both keyword and positional arguments, **keyword arguments must be after positional ones**.
Indeed, in the next cell you'll get a *SyntaxError*. Check it.

In [ ]:
foo( my_key = "its value",120,20,"Hello") #wrong!

Finally, we can set default values for the arguments. Default arguments take the default value during the function call if we do not pass them.

A typical use case is when your algorithm depends on a tolerance, say `tol`, that can be specified by an external user and you decide to set it **by default** to a specific, meaningful, value.

In [ ]:
def very_complicated_algorithm(*data,tol = 1e-12):
  print("tol = ", tol)

very_complicated_algorithm(10,20,30)#tol has its default value
very_complicated_algorithm(10,20,30,tol = 1e-15) #set tolerance to 1e-15

Python modules (next lectures)

In [ ]:
from math import cos

In [ ]:
#numpy, scipy,matplotlib,... next lectures

In [ ]:
cos(20)

### Exercises:

1) Define a string and print all the characters with even index.

2) Define a (non-empty) list of integers, and compute:
- its average
- its minimum
- its max

3) Repeat the same exercise above, but wrapping everything into a function named `get_info` taking as argument a list and returing the average, the minimum and the maximum value.

4) Write a function that takes a natural number `n` and returns the sum of all the natural numbers from 1 to `n`

5) Swap two tuples: given `t1 = (10,20)` and `t2 = (22,88)`, find a way so that `t1 = (22,88)` and `t2 = (10,20)`